title: ThermoPack
description: A ThermoTools Project
show_downloads: true
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-feed
- jekyll-include-cache

url: 'https://thermotools.github.io'

includes_dir: _includes

pypi_url: 'https://pypi.org/project/thermopack/'